### PR TITLE
Switch to std-uritemplate

### LINKED ISSUE #15: swap uri template for std uri template
@andreaTP as soon as you think you're ready, please go ahead and submit a PR here.

### PR DESCRIPTION
**Pull request by andreaTP**
Fix #15

### CODE REVIEW

**Review by baywet — DISMISSED** [review]

**Comment by baywet** [comment]
@andreaTP thanks for the contribution as always!

**Review by baywet — APPROVED** [review]

**Comment by baywet** [comment]
@andreaTP there might be issues with the packaging, see the CI failures for windows

**Comment by andreaTP** [comment]
I can reproduce the issue on Ubuntu, but I'm a bit lost, as the same commands are working on OsX 😞 

If anyone with some Ruby expertise would like to point me in a direction I'll be happy to follow, otherwise, I'll keep digging tomorrow.

**Comment by baywet** [comment]
I've tried looking into it for the past hour, but I'm not super pro-efficient with ruby. As far as I know bundle exec restricts the context and access to global gems. But from my understanding, this shouldn't be an issue in our case. I can see you've already looked into caching. I'm not sure how even the first commit could have a cache hit (but then again, so does MacOS), maybe it's because the Gemfile.lock is NOT present?.
Also it seems to work fine on windows.

**Comment by andreaTP** [comment]
Thanks a lot @baywet for the effort in looking into this, I'll go in the rabbit hole tomorrow, possibly asking on some Ruby channels.

Super interesting that it's working on Win as well!

**Comment by andreaTP** [comment]
The issue is fixed and the tests are green on my fork:
https://github.com/andreaTP/kiota-abstractions-ruby/actions/runs/6096274750/job/16541591070

**Review by baywet — APPROVED** [review]
Thanks for looking into this, what was the issue at then end of the day?

**Comment by baywet** [comment]
Hum... I guess this was the issue

https://github.com/std-uritemplate/std-uritemplate/compare/0.0.38...0.0.39#diff-7708a3635247efbf999cce5719387062c6ff1031150685d5e54bf7a3d24b1859L6

**Comment by andreaTP** [comment]
> what was the issue at then end of the day?

I'm convinced it was the casing of the filename ...
Since I was at it I improved the overall package information etc.

**Pull request merged**
